### ISSUE TITLE
Registro de Proveedores-FRONT

### ISSUE THREAD

**Issue by rodrigo-hp** [casgroup-dev/BFF#1]
- [x] Agregar ruta del componente (dirección URL al componente)
- [x] Crear front de registro del esquema Companies. Una empresa debe soportar múltiples rubros.
1. Razón Social
2. Nombre de Fantasía
3. RUT
4. Nombre de representante legal
5. Correo electrónico de representante legal
6. Teléfono de representante legal
7. Rubro(s)

- [x] Crear validación de inputs
- [x] Construir API de conexión con back (recibir respuesta)
- [x] Simular error desde la respuesta
- [x] Simular prellenado de campos editables y no editables

Se recomienda crear un Mock-Up primero que luego vaya adjunto a un Pull Request.

Link a Issue de BACK asociado: https://github.com/casgroup-dev/users/issues/14

**Comment by SetaSouto** [comment]
Esta issue está desactualizada y ya está funcionando el register salvo por los rubros/industrias que se tiene que hacer con el dropdown. Issue asociada #12
