### ISSUE TITLE
Implementar lógica tras la vista de Registro

### ISSUE THREAD

**Issue by martinpanza** [casgroup-dev/BFF#2]
- [x] 1. Realizar llamado a la API de shadowUsers

- [x] 2. Verificar si el mail es un shadowUser

- [x] 3. Cargar el formulario desde proveedores con campos rellenos

- [x] 4. Evolución del shadowUser a User

- [x] 5. Manejo de Errores

**Comment by SetaSouto** [comment]
Esto quedó listo con el merge de branch `register` si no me equivoco, pero bueno, den `dev` ya está funcionando.
