### ISSUE TITLE
Parsear lista de rubros del servicio de impuestos internos

### ISSUE THREAD

**Issue by martinpanza** [casgroup-dev/BFF#7]
http://www.sii.cl/catastro/codigos.htm

Parsear esta lista para hacer un arbol de rubros.
Esta lista debe mostrarse al nuevo usuario en el formulario para que elija sus rubros

**Comment by xZevalx** [comment]
Lista de tareas:

- [x] Obtener lista desde el link y parsearla
- [x] Crear esquemas para la base de datos
- [x] Poblar la base de datos con script automático

**Comment by xZevalx** [comment]
Esta issue debió escribirse en el repo users
